// Generated by gencpp from file peps/gps_data.msg
// DO NOT EDIT!


#ifndef PEPS_MESSAGE_GPS_DATA_H
#define PEPS_MESSAGE_GPS_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace peps
{
template <class ContainerAllocator>
struct gps_data_
{
  typedef gps_data_<ContainerAllocator> Type;

  gps_data_()
    : beacon_1()
    , beacon_2()  {
    }
  gps_data_(const ContainerAllocator& _alloc)
    : beacon_1(_alloc)
    , beacon_2(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _beacon_1_type;
  _beacon_1_type beacon_1;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _beacon_2_type;
  _beacon_2_type beacon_2;




  typedef boost::shared_ptr< ::peps::gps_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::peps::gps_data_<ContainerAllocator> const> ConstPtr;

}; // struct gps_data_

typedef ::peps::gps_data_<std::allocator<void> > gps_data;

typedef boost::shared_ptr< ::peps::gps_data > gps_dataPtr;
typedef boost::shared_ptr< ::peps::gps_data const> gps_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::peps::gps_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::peps::gps_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace peps

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'peps': ['/home/dawid/Pulpit/peps_testy/ws/src/peps/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::peps::gps_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::peps::gps_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::peps::gps_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::peps::gps_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::peps::gps_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::peps::gps_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::peps::gps_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "47b81c8c692416b6c155fcbe00080eb3";
  }

  static const char* value(const ::peps::gps_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x47b81c8c692416b6ULL;
  static const uint64_t static_value2 = 0xc155fcbe00080eb3ULL;
};

template<class ContainerAllocator>
struct DataType< ::peps::gps_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "peps/gps_data";
  }

  static const char* value(const ::peps::gps_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::peps::gps_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point beacon_1\n\
geometry_msgs/Point beacon_2\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::peps::gps_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::peps::gps_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.beacon_1);
      stream.next(m.beacon_2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gps_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::peps::gps_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::peps::gps_data_<ContainerAllocator>& v)
  {
    s << indent << "beacon_1: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.beacon_1);
    s << indent << "beacon_2: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.beacon_2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PEPS_MESSAGE_GPS_DATA_H
